### ISSUE TITLE
gem version detection

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [ksangers/uamp-dev-environment#12]
Add line 381 you use `GEM_BIN=$(which gem2.2 || which gem)` which is triggered when ubuntu version is less then ubuntu 16. You stated that only versions gem2.2 and up should be targeted but your command checks if gem2.2 exists if not it falls back to `which gem` which can point to a version below 2.2.

**Comment by ksangers** [comment]
I've clearified the code.

**Comment by GeoffreyDijkstra** [comment]
Your solution does not resolve this issue: It checks for `gem` (keep in mind for this example it answers 2.1) then it checks if your ubuntu version is below 16 and if it `hash gem2.2` != false then it uses 2.2. So when this command fails it still uses 2.1 which you do not want. I will see if I can come up with a better solution and make a pull request.

**Comment by ksangers** [comment]
There is no need to come up with an alternative. the fallback is only in place if 2.2 is not available (which it should be anyway)
