### ISSUE TITLE
MySQL-Server breaking script non-verbose

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [ksangers/uamp-dev-environment#5]
Running the script without verbose parameter, the script hangs at "Installing software".
When enabling the -v option I noticed it's because of the mysql-server package which requires you to enter a password.
![screen1](https://cloud.githubusercontent.com/assets/17547877/13396612/eb9aede8-def5-11e5-8d82-a36a2c2f46bd.png)

**Comment by ksangers** [comment]
@GeoffreyDijkstra Good point. I don't have a proper solution for this yet. You can however `apt-get install mysql-server` before running this script to circumvent this.

**Comment by GeoffreyDijkstra** [comment]
@ksangers Small edit on this subject, after mysql dialog I get even more dialogs which all are breaking the non-verbose option so -v should always be included. Also found that oracle-java8-installer license agreement (with -v) is breaking the script it should display a second dialog but hangs after hitting "OK" in the first one.

**Comment by ksangers** [comment]
@GeoffreyDijkstra If you have the solution to the issue please create a new pull request and I'll see if I can merge them
